import {
	generateOpenApiArtifacts,
	type GenerateOpenApiArtifactsOptions,
} from './openapi-generator.js';
import type { OpenApiDocument, OpenApiMethodProjection } from './openapi-types.js';
import { renderScalarHtml } from './scalar-html.js';
export {
	resolveGeneratedDocsResponse,
	type GeneratedDocsResponse,
	type GeneratedDocsRuntimeArtifacts,
	type ResolveGeneratedDocsResponseOptions,
} from './docs-runtime.js';

export type GenerateDocsArtifactsOptions = GenerateOpenApiArtifactsOptions;

export type GeneratedDocsArtifacts = {
	json: OpenApiDocument;
	html: string;
	methods: OpenApiMethodProjection[];
};

export type RenderGeneratedDocsArtifactsModuleOptions = {
	jsonExportName?: string;
	htmlExportName?: string;
	methodsExportName?: string;
	runtimeExportName?: string;
};

export function generateDocsArtifacts(options: GenerateDocsArtifactsOptions): GeneratedDocsArtifacts {
	const artifacts = generateOpenApiArtifacts(options);
	return {
		json: artifacts.document,
		html: artifacts.html,
		methods: artifacts.projections,
	};
}

function renderInlinedGeneratedDocsRuntimeModule(): string {
	const scalarHtmlSource = renderScalarHtml.toString();

	return [
		'type OpenApiSchema = {',
		'  $ref?: string;',
		'  type?: string;',
		'  title?: string;',
		'  description?: string;',
		'  items?: OpenApiSchema;',
		'  properties?: Record<string, OpenApiSchema>;',
		'  additionalProperties?: OpenApiSchema;',
		'  required?: string[];',
		'  anyOf?: OpenApiSchema[];',
		'  enum?: Array<string | number | boolean | null>;',
		'  nullable?: boolean;',
		'};',
		'',
		'type OpenApiDocument = {',
		"  openapi: '3.1.0';",
		'  info: {',
		'    title: string;',
		'    version: string;',
		'    description?: string;',
		'  };',
		'  tags?: Array<{',
		'    name: string;',
		'    description?: string;',
		'  }>;',
		'  paths: Record<',
		'    string,',
		'    {',
		'      get?: OpenApiOperation;',
		'      post?: OpenApiOperation;',
		'    }',
		'  >;',
		'  components?: {',
		'    schemas: Record<string, OpenApiSchema>;',
		'  };',
		'};',
		'',
		'type OpenApiOperation = {',
		'  operationId: string;',
		'  summary?: string;',
		'  description?: string;',
		'  tags?: string[];',
		'  requestBody?: {',
		'    required: boolean;',
		'    content: {',
		"      'application/json': {",
		'        schema: OpenApiSchema;',
		'      };',
		'    };',
		'  };',
		'  responses: {',
		"    '200': {",
		'      description: string;',
		'      content: {',
		"        'application/json': {",
		'          schema: OpenApiSchema;',
		'        };',
		'      };',
		'    };',
		'  };',
		'};',
		'',
		"type OpenApiMethodEffects = {",
		"  receiverMutability: 'none' | 'immutable' | 'mutable';",
		'  mutatesReceiver: boolean;',
		'  externalSideEffects: boolean;',
		"  executionPurity: 'pure' | 'impure' | 'unknown';",
		'  reason: string;',
		'};',
		'',
		"type OpenApiMemberAbiFlags = {",
		'  static: boolean;',
		'  async: boolean;',
		'  readonly: boolean;',
		'  abstract: boolean;',
		"  visibility: 'public' | 'protected' | 'private';",
		'  override: boolean;',
		'  deprecated: boolean;',
		'  export: boolean;',
		'};',
		'',
		"type OpenApiNodeAbiFlags = {",
		'  containsThis: boolean;',
		'  hasAsyncFunctions: boolean;',
		'  awaitContext: boolean;',
		'  optionalChain: boolean;',
		'  hasImplicitReturn: boolean;',
		'  hasExplicitReturn: boolean;',
		'};',
		'',
		"type OpenApiSymbolSpace = 'value' | 'type' | 'namespace';",
		'',
		"type OpenApiSymbolKind =",
		"  | 'unknown'",
		"  | 'function'",
		"  | 'method'",
		"  | 'property'",
		"  | 'accessor'",
		"  | 'constructor'",
		"  | 'class'",
		"  | 'interface'",
		"  | 'typeAlias'",
		"  | 'typeParameter'",
		"  | 'enum'",
		"  | 'enumMember'",
		"  | 'module'",
		"  | 'namespace'",
		"  | 'signature'",
		"  | 'alias'",
		"  | 'prototype'",
		"  | 'objectLiteral'",
		"  | 'typeLiteral';",
		'',
		'type OpenApiRelationTargetRef = {',
		'  name: string;',
		'  path?: string[];',
		'};',
		'',
		'type OpenApiSymbolRelationSet = {',
		'  aliasOf?: OpenApiRelationTargetRef;',
		'  instantiatedFrom?: OpenApiRelationTargetRef;',
		'  extends?: OpenApiRelationTargetRef[];',
		'  implements?: OpenApiRelationTargetRef[];',
		'  memberOf?: OpenApiRelationTargetRef;',
		'  declaresTypeParameters?: string[];',
		'  constrainedBy?: OpenApiRelationTargetRef[];',
		'};',
		'',
		'type OpenApiSymbolSemanticFlags = {',
		'  symbolKind: OpenApiSymbolKind;',
		'  spaces: OpenApiSymbolSpace[];',
		'  isAlias: boolean;',
		'  isOptional: boolean;',
		'  isTypeOnly: boolean;',
		'  isValueLike: boolean;',
		'  isTypeLike: boolean;',
		'  isNamespaceLike: boolean;',
		'};',
		'',
		'type OpenApiMethodProjection = {',
		'  methodName: string;',
		"  httpMethod?: 'get' | 'post';",
		'  httpPath: string;',
		'  requestSchema: OpenApiSchema;',
		'  responseSchema: OpenApiSchema;',
		'  requestRequired: boolean;',
		'  effects: OpenApiMethodEffects;',
		'  memberAbiFlags: OpenApiMemberAbiFlags;',
		'  nodeAbiFlags: OpenApiNodeAbiFlags;',
		'  genericTypeParameters: string[];',
		'  parameterNames: string[];',
		'  parameterOptionalFlags: boolean[];',
		'  parameterRestFlags: boolean[];',
		'  parameterTypeTexts: string[];',
		'  resultTypeText: string;',
		'  symbolSemanticFlags: OpenApiSymbolSemanticFlags;',
		'  symbolRelations: OpenApiSymbolRelationSet;',
		'  components?: {',
		'    schemas: Record<string, OpenApiSchema>;',
		'  };',
		'  docs?: {',
		'    summary?: string;',
		'    description?: string;',
		'    params?: Record<string, string>;',
		'    returnsDescription?: string;',
		'    tags?: string[];',
		'  };',
		'};',
		'',
		'type GeneratedDocsRuntimeArtifacts = {',
		'  json: {',
		'    openapi: string;',
		'    info: {',
		'      title: string;',
		'      version: string;',
		'      description?: string;',
		'    };',
		'  };',
		'  html: string;',
		'  methods: ReadonlyMap<string, {',
		'    methodName: string;',
		'    httpPath: string;',
		'    requestSchema: unknown;',
		'    responseSchema: unknown;',
		'    requestRequired: boolean;',
		'    effects: OpenApiMethodEffects;',
		'    components?: {',
		'      schemas: Record<string, unknown>;',
		'    };',
		'    docs?: {',
		'      summary?: string;',
		'      description?: string;',
		'      returnsDescription?: string;',
		'      tags?: string[];',
		'      params?: Record<string, string>;',
		'    };',
		'  }>;',
		'};',
		'',
		'type ResolveGeneratedDocsResponseOptions = {',
		'  method: string;',
		'  requestUrl: URL;',
		'  acceptHeader?: string;',
		'  routeMethodName?: string | null;',
		'  namespacePath: string;',
		'  artifacts: GeneratedDocsRuntimeArtifacts;',
		'  buildMethodTitle?: (methodName: string) => string;',
		'  buildMethodDescription?: (methodName: string) => string;',
		'  methodVersion?: string;',
		'};',
		'',
		'type GeneratedDocsResponse = {',
		'  status: number;',
		"  kind: 'json' | 'html';",
		'  body: unknown;',
		'};',
		'',
		'type RenderScalarHtmlOptions = {',
		'  pageTitle?: string;',
		'  cdnScriptUrl?: string;',
		'  customCss?: string;',
		'};',
		'',
		'function escapeHtml(value: string): string {',
		'  return value',
		"    .replaceAll('&', '&amp;')",
		"    .replaceAll('<', '&lt;')",
		"    .replaceAll('>', '&gt;')",
		'    .replaceAll(\'"\', \"&quot;\")',
		"    .replaceAll(\"'\", '&#39;');",
		'}',
		'',
		`const renderScalarHtml: (document: OpenApiDocument, options?: RenderScalarHtmlOptions) => string = ${scalarHtmlSource};`,
		'',
		'function resolveGeneratedDocsResponse(options: ResolveGeneratedDocsResponseOptions): GeneratedDocsResponse | null {',
		"  const normalizedMethod = options.method.toUpperCase();",
		"  if (normalizedMethod !== 'GET') {",
		'    return null;',
		'  }',
		'',
		"  const docsJsonPath = `${trimTrailingSlash(options.namespacePath)}/__docs/openapi.json`;",
		'  if (options.requestUrl.pathname === docsJsonPath) {',
		'    return {',
		'      status: 200,',
		"      kind: 'json',",
		'      body: options.artifacts.json,',
		'    };',
		'  }',
		'',
		"  const docsHtmlPath = `${trimTrailingSlash(options.namespacePath)}/__docs/scalar`;",
		'  if (options.requestUrl.pathname === docsHtmlPath) {',
		'    return {',
		'      status: 200,',
		"      kind: 'html',",
		'      body: options.artifacts.html,',
		'    };',
		'  }',
		'',
		'  if (!options.routeMethodName) {',
		'    return null;',
		'  }',
		'',
		'  const projection = options.artifacts.methods.get(options.routeMethodName);',
		'  if (!projection) {',
		'    return {',
		'      status: 404,',
		"      kind: 'json',",
		'      body: { ok: false, error: `No generated docs found for ${options.routeMethodName}.` },',
		'    };',
		'  }',
		'',
		'  const document = buildOpenApiMethodDocumentFromProjection(projection as OpenApiMethodProjection, {',
		'    title: options.buildMethodTitle?.(options.routeMethodName) ?? options.routeMethodName,',
		'    version: options.methodVersion ?? options.artifacts.json.info.version,',
		'    description: options.buildMethodDescription?.(options.routeMethodName)',
		'      ?? `Generated method documentation for ${options.routeMethodName}.`,',
		'  });',
		'',
		"  if (resolveDocsFormat(options.requestUrl, options.acceptHeader) === 'json') {",
		'    return {',
		'      status: 200,',
		"      kind: 'json',",
		'      body: document,',
		'    };',
		'  }',
		'',
		'  return {',
		'    status: 200,',
		"    kind: 'html',",
		'    body: renderScalarHtml(document, {',
		'      pageTitle: options.buildMethodTitle?.(options.routeMethodName) ?? options.routeMethodName,',
		'    }),',
		'  };',
		'}',
		'',
		'function buildOpenApiMethodDocumentFromProjection(',
		'  projection: OpenApiMethodProjection,',
		'  options: { title: string; version: string; description?: string },',
		'): OpenApiDocument {',
		'  const tagNames = projection.docs?.tags?.length',
		'    ? projection.docs.tags',
		'    : inferTags(projection.methodName);',
		'',
		'  return {',
		"    openapi: '3.1.0',",
		'    info: {',
		'      title: options.title,',
		'      version: options.version,',
		'      ...(options.description ? { description: options.description } : {}),',
		'    },',
		'    ...(tagNames.length > 0 ? { tags: tagNames.map((name) => ({ name })) } : {}),',
		'    paths: {',
		'      [projection.httpPath]: {',
		"        [projection.httpMethod ?? 'post']: {",
		'          operationId: projection.methodName,',
		'          ...(projection.docs?.summary ? { summary: projection.docs.summary } : {}),',
		'          ...(projection.docs?.description ? { description: projection.docs.description } : {}),',
		'          ...(projection.docs?.tags?.length ? { tags: projection.docs.tags } : { tags: inferTags(projection.methodName) }),',
		"          ...(projection.httpMethod === 'get' ? {} : {",
		'            requestBody: {',
		'              required: projection.requestRequired,',
		'              content: {',
		"                'application/json': {",
		'                  schema: projection.requestSchema,',
		'                },',
		'              },',
		'            },',
		'          }),',
		'          responses: {',
		"            '200': {",
		'              description: projection.docs?.returnsDescription ?? `Result of ${projection.methodName}.`,',
		'              content: {',
		"                'application/json': {",
		'                  schema: projection.responseSchema,',
		'                },',
		'              },',
		'            },',
		'          },',
		'        },',
		'      },',
		'    },',
		'    ...(projection.components?.schemas ? { components: { schemas: projection.components.schemas } } : {}),',
		'  };',
		'}',
		'',
		'function inferTags(methodName: string): string[] {',
		"  const firstDot = methodName.indexOf('.');",
		'  if (firstDot <= 0) {',
		"    return ['rpc'];",
		'  }',
		'  return [methodName.slice(0, firstDot)];',
		'}',
		'',
		"function resolveDocsFormat(requestUrl: URL, acceptHeader: string | undefined): 'json' | 'html' {",
		"  const explicit = requestUrl.searchParams.get('__docs')?.toLowerCase();",
		"  if (explicit === 'json') return 'json';",
		"  if (explicit === 'html') return 'html';",
		"  if (acceptHeader?.includes('application/vnd.nrpc.openapi+json')) return 'json';",
		"  return 'html';",
		'}',
		'',
		'function trimTrailingSlash(value: string): string {',
		"  return value.endsWith('/') ? value.slice(0, -1) : value;",
		'}',
		'',
	].join('\n');
}

export function renderGeneratedDocsArtifactsModule(
	artifacts: GeneratedDocsArtifacts,
	options: RenderGeneratedDocsArtifactsModuleOptions = {},
): string {
	const jsonExportName = options.jsonExportName ?? 'docsJson';
	const htmlExportName = options.htmlExportName ?? 'docsHtml';
	const methodsExportName = options.methodsExportName ?? 'docsMethods';
	const runtimeExportName = options.runtimeExportName ?? 'generatedDocsRuntime';
	const inlinedRuntimeModule = renderInlinedGeneratedDocsRuntimeModule();
    const methodsEntriesText = JSON.stringify(artifacts.methods.map((projection) => [projection.methodName, projection]), null, 2);

	return [
		'// AUTO-GENERATED FILE. DO NOT EDIT.',
		'',
		inlinedRuntimeModule,
		'',
		`export const ${jsonExportName} = ${JSON.stringify(artifacts.json, null, 2)};`,
		'',
		`export const ${htmlExportName} = ${JSON.stringify(artifacts.html)};`,
		'',
		`export const ${methodsExportName}: ReadonlyMap<string, { methodName: string; httpPath: string; requestSchema: unknown; responseSchema: unknown; requestRequired: boolean; effects: OpenApiMethodEffects; genericTypeParameters?: string[]; parameterNames?: string[]; parameterOptionalFlags?: boolean[]; parameterRestFlags?: boolean[]; parameterTypeTexts?: string[]; resultTypeText?: string; symbolSemanticFlags?: OpenApiSymbolSemanticFlags; symbolRelations?: OpenApiSymbolRelationSet; memberAbiFlags?: OpenApiMemberAbiFlags; nodeAbiFlags?: OpenApiNodeAbiFlags; components?: { schemas: Record<string, unknown> }; docs?: { summary?: string; description?: string; returnsDescription?: string; tags?: string[]; params?: Record<string, string> } }> = new Map(${methodsEntriesText}) as ReadonlyMap<string, { methodName: string; httpPath: string; requestSchema: unknown; responseSchema: unknown; requestRequired: boolean; effects: OpenApiMethodEffects; genericTypeParameters?: string[]; parameterNames?: string[]; parameterOptionalFlags?: boolean[]; parameterRestFlags?: boolean[]; parameterTypeTexts?: string[]; resultTypeText?: string; symbolSemanticFlags?: OpenApiSymbolSemanticFlags; symbolRelations?: OpenApiSymbolRelationSet; memberAbiFlags?: OpenApiMemberAbiFlags; nodeAbiFlags?: OpenApiNodeAbiFlags; components?: { schemas: Record<string, unknown> }; docs?: { summary?: string; description?: string; returnsDescription?: string; tags?: string[]; params?: Record<string, string> } }>;`,
		'',
		`const ${runtimeExportName}Artifacts: GeneratedDocsRuntimeArtifacts = {`,
		`  json: ${jsonExportName},`,
		`  html: ${htmlExportName},`,
		`  methods: ${methodsExportName} as ReadonlyMap<string, { methodName: string; httpPath: string; requestSchema: unknown; responseSchema: unknown; requestRequired: boolean; effects: OpenApiMethodEffects; components?: { schemas: Record<string, unknown> }; docs?: { summary?: string; description?: string; returnsDescription?: string; tags?: string[]; params?: Record<string, string> } }>,`,
		`};`,
		'',
		`export const ${runtimeExportName} = {`,
		`  ...${runtimeExportName}Artifacts,`,
		`  routeMethodNameByDocsPath: new Map([...${methodsExportName}.values()].map((projection) => [\`${'${projection.httpPath}'}/_docs\`, projection.methodName])),`,
		`  resolve(request: Request) {`,
		`    const url = new URL(request.url);`,
		`    if (request.method === 'GET' && url.pathname === '/docs/openapi.json') {`,
		`      return { status: 200, kind: 'json', body: ${jsonExportName} } as const;`,
		`    }`,
		`    if (request.method === 'GET' && url.pathname === '/docs') {`,
		`      return resolveGeneratedDocsResponse({`,
		`        method: request.method,`,
		`        requestUrl: new URL(\`${'${url.origin}'}/docs/__docs/scalar${'${url.search}'}\`),`,
		`        acceptHeader: request.headers.get('accept') ?? undefined,`,
		`        namespacePath: '/docs',`,
		`        artifacts: ${runtimeExportName}Artifacts,`,
		`      });`,
		`    }`,
		`    const routeMethodName = this.routeMethodNameByDocsPath.get(url.pathname);`,
		`    if (request.method === 'GET' && routeMethodName) {`,
		`      return resolveGeneratedDocsResponse({`,
		`        method: request.method,`,
		`        requestUrl: url,`,
		`        acceptHeader: request.headers.get('accept') ?? undefined,`,
		`        routeMethodName,`,
		`        namespacePath: '/docs',`,
		`        artifacts: ${runtimeExportName}Artifacts,`,
		`      });`,
		`    }`,
		`    return null;`,
		`  },`,
		`};`,
		'',
	].join('\n');
}
