import { pascalize, toMcpToolName, type OpenApiSurfaceMethod } from './renderer-shared.js';

export function renderOpenApiMcpTools(input: { globalName: string; methods: OpenApiSurfaceMethod[] }): string {
  const methodSpecs = input.methods.map((method) => ({
    name: toMcpToolName(input.globalName, method.methodName),
    methodName: method.methodName,
    description: buildMcpToolDescription(method),
    inputSchema: method.inputJsonSchema,
    route: {
      httpMethod: method.httpMethod,
      httpPath: method.httpPath,
      requestContentType: method.requestContentType,
      requestBodyKind: method.requestBodyKind,
      responseContentType: method.responseContentType,
      graphqlOperationName: method.graphqlOperationName,
      graphqlRootFieldNames: method.graphqlRootFieldNames,
      graphqlQuery: method.graphqlQuery,
    },
  }));

  return [
    '// AUTO-GENERATED FILE. DO NOT EDIT.',
    'export type OpenApiMcpToolResponse = {',
    '  content: Array<{ type: "text"; text: string }>; ',
    '  role?: string;',
    '};',
    '',
    'export type OpenApiMcpToolDefinition = {',
    '  name: string;',
    '  description: string;',
    '  inputSchema: Record<string, unknown>;',
    '  handler: (args: Record<string, unknown>) => Promise<OpenApiMcpToolResponse>;',
    '};',
    '',
    'export type OpenApiMcpToolOptions = {',
    '  baseUrl: string;',
    '  fetch?: typeof fetch;',
    '  defaultHeaders?: Record<string, string>;',
    '};',
    '',
    'type GeneratedOpenApiRoute = {',
    '  httpMethod: string;',
    '  httpPath: string;',
    '  requestContentType?: string;',
    '  requestBodyKind: "none" | "json" | "form" | "binary" | "text";',
    '  responseContentType?: string;',
    '  graphqlOperationName?: string;',
    '  graphqlRootFieldNames?: string[];',
    '  graphqlQuery?: string;',
    '};',
    '',
    `export const ${input.globalName}McpToolSpecs = ${JSON.stringify(methodSpecs)} as const;`,
    '',
    'function toTextResponse(value: unknown): OpenApiMcpToolResponse {',
    '  return {',
    '    content: [',
    '      {',
    '        type: "text",',
    '        text: JSON.stringify(value, null, 2),',
    '      },',
    '    ],',
    '  };',
    '}',
    '',
    'function toFormUrlEncoded(value: unknown): string {',
    '  if (!value || typeof value !== "object") {',
    '    return "";',
    '  }',
    '  const params = new URLSearchParams();',
    '  for (const [key, entry] of Object.entries(value as Record<string, unknown>)) {',
    '    if (entry === undefined || entry === null) continue;',
    '    if (Array.isArray(entry)) {',
    '      for (const item of entry) {',
    '        params.append(key, String(item));',
    '      }',
    '      continue;',
    '    }',
    '    params.set(key, String(entry));',
    '  }',
    '  return params.toString();',
    '}',
    '',
    'function toBinaryBody(value: unknown): BodyInit {',
    '  if (value instanceof Uint8Array) return value;',
    '  if (value instanceof ArrayBuffer) return value;',
    '  if (value instanceof Blob) return value;',
    '  if (typeof value === "string") return value;',
    '  return JSON.stringify(value);',
    '}',
    '',
    'async function parseResponseBody(response: Response, route: GeneratedOpenApiRoute): Promise<unknown> {',
    '  if (response.status === 204 || response.status === 205) {',
    '    return null;',
    '  }',
    '  const contentType = response.headers.get("content-type") ?? route.responseContentType ?? "";',
    '  if (contentType.includes("application/json") || contentType.endsWith("+json")) {',
    '    const parsed = await response.json();',
    '    if (route.graphqlOperationName && parsed && typeof parsed === "object") {',
    '      const data = (parsed as { data?: unknown }).data;',
    '      if (!route.graphqlRootFieldNames || route.graphqlRootFieldNames.length === 0) return data;',
    '      if (route.graphqlRootFieldNames.length === 1 && data && typeof data === "object") {',
    '        return (data as Record<string, unknown>)[route.graphqlRootFieldNames[0]!];',
    '      }',
    '      return data;',
    '    }',
    '    return parsed;',
    '  }',
    '  if (contentType.startsWith("text/")) {',
    '    return await response.text();',
    '  }',
    '  if (contentType.includes("application/octet-stream") || contentType.startsWith("image/")) {',
    '    return Array.from(new Uint8Array(await response.arrayBuffer()));',
    '  }',
    '  const raw = await response.text();',
    '  if (!raw) return null;',
    '  try {',
    '    return JSON.parse(raw);',
    '  } catch {',
    '    return raw;',
    '  }',
    '}',
    '',
    `export function create${pascalize(input.globalName)}McpTools(options: OpenApiMcpToolOptions): OpenApiMcpToolDefinition[] {`,
    '  const fetchImpl = options.fetch ?? fetch;',
    `  return ${input.globalName}McpToolSpecs.map((spec) => ({`,
    '    name: spec.name,',
    '    description: spec.description,',
    '    inputSchema: spec.inputSchema as Record<string, unknown>,',
    '    handler: async (args) => {',
    '      const route = spec.route as GeneratedOpenApiRoute;',
    '      const url = new URL(route.httpPath, options.baseUrl);',
    '      const headers: Record<string, string> = { ...(options.defaultHeaders ?? {}) };',
    '      const input = args && typeof args === "object" ? args as Record<string, unknown> : {};',
    '      const pathArgs = input.path && typeof input.path === "object" ? input.path as Record<string, unknown> : {};',
    '      const queryArgs = input.query && typeof input.query === "object" ? input.query as Record<string, unknown> : {};',
    '      const headerArgs = input.header && typeof input.header === "object" ? input.header as Record<string, unknown> : {};',
    '',
    '      for (const [key, value] of Object.entries(pathArgs)) {',
    '        url.pathname = url.pathname.replace(`{${key}}`, encodeURIComponent(String(value)));',
    '      }',
    '      for (const [key, value] of Object.entries(queryArgs)) {',
    '        if (value === undefined || value === null) continue;',
    '        if (Array.isArray(value)) {',
    '          for (const item of value) {',
    '            url.searchParams.append(key, String(item));',
    '          }',
    '          continue;',
    '        }',
    '        url.searchParams.set(key, String(value));',
    '      }',
    '      for (const [key, value] of Object.entries(headerArgs)) {',
    '        if (typeof value === "string" && value.length > 0) {',
    '          headers[key] = value;',
    '        }',
    '      }',
    '',
    '      const init: RequestInit = { method: route.httpMethod, headers };',
    '      if (input.body !== undefined && route.requestBodyKind !== "none") {',
    '        switch (route.requestBodyKind) {',
    '          case "form":',
    '            init.body = toFormUrlEncoded(input.body);',
    '            headers["content-type"] = route.requestContentType ?? "application/x-www-form-urlencoded";',
    '            break;',
    '          case "binary":',
    '            init.body = toBinaryBody(input.body);',
    '            if (route.requestContentType) headers["content-type"] = route.requestContentType;',
    '            break;',
    '          case "text":',
    '            init.body = typeof input.body === "string" ? input.body : String(input.body);',
    '            headers["content-type"] = route.requestContentType ?? "text/plain";',
    '            break;',
    '          case "json":',
    '          default:',
    '            init.body = JSON.stringify(input.body);',
    '            headers["content-type"] = route.requestContentType ?? "application/json";',
    '            break;',
    '        }',
    '      }',
    '      if (route.graphqlOperationName) {',
    '        const graphQlVariables = input.body !== undefined ? input.body : input;',
    '        init.body = JSON.stringify({',
    '          operationName: route.graphqlOperationName,',
    '          query: route.graphqlQuery,',
    '          ...(graphQlVariables && typeof graphQlVariables === "object" ? graphQlVariables : { variables: graphQlVariables }),',
    '        });',
    '        headers["content-type"] = route.requestContentType ?? "application/json";',
    '      }',
    '',
    '      const response = await fetchImpl(url, init);',
    '      const body = await parseResponseBody(response, route);',
    '      return toTextResponse({',
    '        ok: response.ok,',
    '        status: response.status,',
    '        statusText: response.statusText,',
    '        url: url.toString(),',
    '        headers: Object.fromEntries(response.headers.entries()),',
    '        body,',
    '      });',
    '    },',
    '  }));',
    '}',
    '',
  ].join('\n');
}

function buildMcpToolDescription(method: OpenApiSurfaceMethod): string {
  const summary = method.summary?.trim() || `Invoke ${method.httpMethod} ${method.httpPath}`;
  const description = method.description?.trim();
  return [
    summary,
    `HTTP: ${method.httpMethod} ${method.httpPath}`,
    ...(description ? [description] : []),
  ].join('\n');
}